services:
  - type: web
    name: collaborative-coding-platform
    env: docker
    plan: free
    dockerfilePath: ./02-end-to-end/online-coding-interviews/Dockerfile
    dockerContext: ./02-end-to-end/online-coding-interviews
    envVars:
      - key: PORT
        value: 8000
